### ISSUE TITLE
Add APK to release

### ISSUE THREAD

**Issue by NoozAbooz** [BNH440/vrc-tracker#8]
Hello, I reside in Canada and this app is not available for me on Google Play. Could you please include a apk with the github releases so I can install it? Thanks.

**Comment by BNH440** [comment]
Sure! I can add it later today. Also not entirely sure why it’s not available in Canada, I’ll check the Google play settings.

**Comment by BNH440** [comment]
Done, I added the apk to the latest release and enabled publishing in Canada (but that will take time for google to approve it).
